import Foundation

private func j(_ s: String) -> Prompt { Prompt(text: s, kind: .journal, theme: .nature) }
private func c(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .nature) }

extension PromptLibrary {
    static let nature: [Prompt] = [
        // — Journal —
        j("Describe the sky right now without using the word 'blue.'"),
        j("What's the oldest living thing you've stood beside?"),
        j("Where do you go to feel small in a good way?"),
        j("What did the wind do today?"),
        j("Describe a tree you'd recognize anywhere."),
        j("When did you last watch water move?"),
        j("What season are you, lately?"),
        j("Describe the ground beneath you right now."),
        j("What bird have you noticed more than once?"),
        j("Write about the last sunrise or sunset you actually stopped for."),
        j("What does the air smell like today?"),
        j("Where have you watched something grow?"),
        j("Describe a storm you remember."),
        j("What plant would you want to be tended like?"),
        j("When did nature last surprise you?"),
        j("Describe the light through leaves."),
        j("What's your relationship with the moon these days?"),
        j("Where do you feel the change of seasons first?"),
        j("Write about a body of water you love."),
        j("What animal would understand you?"),
        j("Describe the quietest place you know outdoors."),
        j("What's blooming or fading near you right now?"),
        j("When did you last walk with no destination?"),
        j("Describe the texture of bark, stone, or moss you've touched."),
        j("What weather matches your mood today?"),
        j("Where did you last see the horizon?"),
        j("Write about a garden — yours or someone else's."),
        j("What sound does your favorite landscape make?"),
        j("Describe the coldest you've ever been outside."),
        j("What do you notice about the trees this week?"),
        j("When did you last lie down and look up?"),
        j("Describe a path you've walked many times."),
        j("What's the most alive a place has ever felt to you?"),
        j("Where would you build a small shelter?"),
        j("Write about rain on a window."),
        j("What does the natural world ask of you?"),
        j("Describe a hill, dune, or mountain you've climbed."),
        j("What grows wild where you live?"),
        j("When did you last hold something a plant made — seed, fruit, leaf?"),
        j("Describe dusk where you are."),
        j("What's the farthest you've followed a trail?"),
        j("Where do you feel the seasons turning inside you?"),
        j("Write about the first warm day after a long cold."),
        j("What creature shares your home, invited or not?"),
        j("Describe the way snow, sand, or mud holds a footprint."),
        j("What's a smell that means a particular season to you?"),
        j("When did weather change your plans, for better?"),
        j("Describe a field at a particular hour."),
        j("What part of the day belongs to the birds where you live?"),
        j("Where have you watched the tide, the fog, or the frost arrive?"),
        j("Write about a fire you've sat beside."),
        j("What does the night sky look like from your favorite place?"),
        j("Describe a fruit at the moment it's perfectly ripe."),
        j("When did you last get caught in the rain and not mind?"),
        j("What's the wildest place you've ever slept?"),
        j("Describe the color the world turns just before a storm."),
        j("Where do roots run deep in your life?"),
        j("Write about a leaf you'd keep."),
        j("What's the smallest living thing you've watched closely?"),
        j("Describe the river, creek, or shoreline nearest you."),
        j("When does the light feel best where you live?"),
        j("What would you plant if you knew you'd never see it grow?"),
        j("Describe a meadow, marsh, or wood you can picture with your eyes closed."),
        j("What does the cold teach you?"),
        j("Where have you been still long enough for animals to forget you?"),
        j("Write about the shape of a particular cloud."),
        j("What's a weather you'd travel to feel again?"),
        j("Describe the way frost edges a leaf."),
        j("When did the sea, lake, or sky last make you cry, even a little?"),
        j("What does spring undo in you?"),
        j("Describe the smell of soil after rain."),
        j("Where would you scatter something you've loved?"),
        j("Write about a tree you've watched through seasons."),
        j("What's the most patient thing in nature you admire?"),
        j("Describe how darkness falls where you are."),
        j("When did you last forage, pick, or gather something?"),
        j("What's a sound only this season makes?"),
        j("Describe the warmest light you've ever stood in."),
        j("Where does the wild edge of your town begin?"),
        j("Write about the moment a season tips into the next."),

        // — Creative —
        c("Write from the point of view of a river that's tired of being crossed."),
        c("A forest keeps a record of everyone who passes through. Read an entry."),
        c("Describe the last tree on a hill that's being cleared."),
        c("Write a love story between the tide and the shore."),
        c("A seed remembers the tree it came from. Write its memory."),
        c("Describe a city slowly being reclaimed by green."),
        c("Write the conversation between two old oaks at the edge of a field."),
        c("A mountain dreams. Write what it dreams of."),
        c("Describe the first flower to bloom after a fire."),
        c("Write about a lighthouse keeper and the one storm they'll never forget."),
        c("A migrating bird narrates the journey it's made for ten years."),
        c("Describe rain falling on a place that hasn't seen it in years."),
        c("Write from the perspective of moss reclaiming a forgotten statue."),
        c("A garden grows only at night. Who tends it, and why?"),
        c("Describe the moment a glacier lets go."),
        c("Write a fable in which the wind owes someone a favor."),
        c("A fox leads a lost child home through the snow. Write it."),
        c("Describe a meadow the day before it's mown."),
        c("Write about the last bee in a silent orchard."),
        c("A village lives by the moods of a volcano. Write an ordinary morning."),
        c("Describe a desert that remembers being an ocean."),
        c("Write the diary of a tree planted the day a child was born."),
        c("A storm gathers offshore with a purpose. Reveal it slowly."),
        c("Describe the world from inside a drop of dew at dawn."),
        c("Write about a woman who can hear what the roots are saying."),
        c("A lake freezes over something it would rather keep hidden. Continue."),
        c("Describe the migration of something that has never moved before."),
        c("Write a scene where a forest decides to let someone leave — or not."),
        c("A mushroom network passes a message across a whole valley. Write the message."),
        c("Describe the exact moment night becomes morning in a deep wood."),
        c("Write about the keeper of the last wild garden in a paved world."),
        c("A whale surfaces to tell a sailor one true thing. What is it?"),
        c("Describe a field of grass the moment a great wind arrives."),
        c("Write the story of a stone worn smooth by a particular hand."),
        c("A spring thaw uncovers something the winter buried. Continue."),
        c("Describe a canyon at the hour it holds the most shadow."),
        c("Write from the view of a scarecrow who has watched many harvests."),
        c("A flock of starlings spells a word in the sky. Write what happens next."),
        c("Describe the green that returns to a battlefield."),
        c("Write about a child raised partly by a river."),
        c("A tree is asked to be cut down for a good reason. Give it a voice."),
        c("Describe a tide pool as a small, complete world with its own politics."),
        c("Write the legend of the wind that only blows once a century."),
        c("A gardener plants a tree they'll never sit beneath. Show the planting."),
        c("Describe the first snow in a town that has never seen it."),
        c("Write about the night the fireflies didn't come."),
        c("A mountain pass tells the story of everyone who's tried to cross it."),
        c("Describe an old forest that has decided to move, very slowly."),
        c("Write a scene where the sun rises for the first time in a long winter."),
        c("A river changes course and a town must follow. Write the leaving."),
        c("Describe the moment a chrysalis goes still before it opens."),
        c("Write from the perspective of the oldest tree in a sacred grove."),
        c("A drought ends mid-sentence in someone's prayer. Continue."),
        c("Describe a beach the hour after everyone has gone."),
        c("Write about a creature that only appears in the fog."),
        c("A field of sunflowers all turn the wrong way one morning. Why?"),
        c("Describe the underside of a leaf as a landscape."),
        c("Write the story of a well that has heard every secret in town."),
        c("A storm and a calm trade places for a day. Write it."),
        c("Describe the last hour of autumn before the cold sets in."),
        c("Write about a shepherd who can read the weather in the sheep."),
        c("A forest fire spares one cabin for a reason. Reveal it."),
        c("Describe the sea at the moment it decides to be still."),
        c("Write a myth explaining why the leaves change color."),
        c("A bird builds its nest from things people have lost. Catalog them."),
        c("Describe dawn breaking over a flooded valley."),
        c("Write about the keeper of a seed vault at the end of the world."),
        c("A cave hides a small, persistent light. Follow it inward."),
        c("Describe the way a vine finally reaches the window it was climbing toward."),
        c("Write the conversation between the first and last frost of the year."),
        c("A meadow blooms in a color no one can name. Write the discovery."),
        c("Describe the hush of a snowfall in a sleeping city."),
        c("Write about an island that appears only at low tide."),
        c("A great tree falls in an empty forest. Write who hears it anyway."),
        c("Describe the migration home as a return to a changed place."),
        c("Write the story of a garden planted entirely from memory."),
        c("A river delivers something to the sea it was asked to carry. Reveal it."),
        c("Describe the green smell of the world the morning after a long rain."),
        c("Write about the last warm rock where the lizards gather at season's end.")
    ]
}
