import Foundation

private func j(_ s: String) -> Prompt { Prompt(text: s, kind: .journal, theme: .reflective) }
private func c(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .reflective) }

extension PromptLibrary {
    static let reflective: [Prompt] = [
        // — Journal —
        j("What has quietly stayed with you today?"),
        j("Describe the light wherever you are right now."),
        j("What did today ask of you?"),
        j("Write down something you noticed that no one else did."),
        j("What are you slowly changing your mind about?"),
        j("Name a small mercy from the last day or two."),
        j("What would you tell yourself a year ago?"),
        j("What's a sentence you keep coming back to?"),
        j("Describe a sound from today."),
        j("What felt true this week, even briefly?"),
        j("Who were you with, and what did you carry away?"),
        j("What's unfinished, and how does that sit with you?"),
        j("What did you make room for today?"),
        j("What are you grateful for that's easy to overlook?"),
        j("Where did you feel most like yourself this week?"),
        j("What did you almost say, but didn't?"),
        j("What's one thing you're tired of carrying?"),
        j("Describe the last time you felt genuinely calm."),
        j("What are you pretending not to know?"),
        j("Who do you miss, and what would you say to them?"),
        j("What did your body tell you today?"),
        j("What small kindness did someone show you recently?"),
        j("What are you outgrowing?"),
        j("Name something you're proud of but rarely mention."),
        j("What would 'enough' look like for you right now?"),
        j("What did you avoid today, and why?"),
        j("Describe a place that always settles you."),
        j("What's a fear you've quietly made peace with?"),
        j("What did you learn the hard way?"),
        j("Who taught you something without meaning to?"),
        j("What does rest actually look like for you?"),
        j("What's been asking for your attention lately?"),
        j("Describe yourself the way a kind friend would."),
        j("What's a habit you'd like to keep?"),
        j("What did today smell like?"),
        j("Where are you being too hard on yourself?"),
        j("What's a question you're living inside right now?"),
        j("What would you do with an unhurried hour?"),
        j("What surprised you about yourself this week?"),
        j("What are you ready to forgive — including in yourself?"),

        // — Creative —
        c("Write a scene that begins with a door left open."),
        c("Two strangers share an umbrella. Neither speaks. Write it."),
        c("Describe a city that only exists between 3 and 4 a.m."),
        c("Write the last text message someone never sent."),
        c("A character finds a letter addressed to them in their own handwriting."),
        c("Write about an object that outlived its owner."),
        c("Begin a story with the line: 'By then, the river had changed its mind.'"),
        c("Describe a room by the absence in it."),
        c("Write a conversation where the important thing is never said."),
        c("A clock in an empty house keeps perfect time. Why?"),
        c("Write a memory that may not have happened."),
        c("Describe a color to someone who has never seen it."),
        c("Write the moment just before everything changes."),
        c("A character keeps a list of things they'll do 'someday.' Show us three."),
        c("Write a goodbye that's disguised as a hello."),
        c("Describe weather that matches a feeling you can't name."),
        c("Write about a town where it's always the same season."),
        c("A photograph develops to show something that wasn't there. Continue."),
        c("Write a scene set entirely in a stairwell."),
        c("Describe the inside of a forgotten coat pocket."),
        c("Write a character who collects other people's discarded receipts."),
        c("Begin: 'The map was wrong, and that was the point.'"),
        c("Write a quiet argument between two old friends."),
        c("Describe a house that remembers everyone who lived there."),
        c("Write the story a scar would tell."),
        c("A character can hear one minute into the future. Write a small scene."),
        c("Describe a meal that means more than food."),
        c("Write about the last lit window on a dark street."),
        c("Two people meet again after years and pretend they haven't. Write it."),
        c("Describe a sound that means home."),
        c("Write a scene where rain is the only honest thing."),
        c("A character returns something they borrowed a lifetime ago. Continue."),
        c("Write about a key with no known lock."),
        c("Describe a garden tended by someone who's gone."),
        c("Write the inner voice of someone waiting for news."),
        c("A character writes a review for a place that no longer exists."),
        c("Describe morning as if you've never seen one."),
        c("Write a story that fits inside a single held breath."),
        c("Begin: 'She kept the ticket, though the train had long since left.'"),
        c("Write about a small act of courage no one witnessed.")
    ]
}
