import Foundation

// Per-theme builders (file-private so names don't collide with other packs).
private func pj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .poetry) }
private func pc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .poetry) }
private func dj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .dreams) }
private func dc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .dreams) }
private func lj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .letters) }
private func lc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .letters) }
private func wj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .worldbuilding) }
private func wc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .worldbuilding) }
private func sj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .sparks) }
private func sc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .sparks) }
private func zj(_ s: String) -> Prompt { Prompt(text: s, kind: .journal,  theme: .seasonal) }
private func zc(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .seasonal) }

extension PromptLibrary {

    static let poetry: [Prompt] = [
        pj("Write three lines about this exact moment, no editing."),
        pj("What ordinary object deserves a poem today?"),
        pj("Describe your morning in five words or fewer."),
        pj("What's a metaphor for how you feel right now?"),
        pj("Find a poem in the last thing someone said to you."),
        pj("What color is today, and why?"),
        pj("Write the shortest true thing you can."),
        pj("What sound would your week make as a single note?"),
        pj("Describe light as if it were a feeling."),
        pj("What's the most poetic thing you saw today?"),
        pc("Write a poem that begins and ends with the same line."),
        pc("Write a poem made only of questions."),
        pc("Compose a haiku about something breaking."),
        pc("Write a poem to an emotion you can't name."),
        pc("Write a list poem of small things you'd save from a fire."),
        pc("Write a poem where each line is one breath."),
        pc("Write an ode to something usually ignored."),
        pc("Write a poem in which the seasons argue."),
        pc("Write a poem that is secretly an apology."),
        pc("Write a poem using only words a child would know."),
        pc("Write a love poem to a place, not a person."),
        pc("Write a poem that fits on the back of a receipt."),
        pc("Write a poem where the last word changes everything before it."),
        pc("Write a poem about the color of a sound."),
        pc("Write a poem that is a set of instructions."),
        pc("Write a poem for the person you were ten years ago."),
        pc("Write a poem in which silence is a character."),
        pc("Write a poem that begins 'Tell me about the—'"),
        pc("Write a two-line poem with a turn in the middle."),
        pc("Write a poem about a door."),
    ]

    static let dreams: [Prompt] = [
        dj("Write down a dream you still remember, however fragmentary."),
        dj("What recurring image shows up when you're stressed?"),
        dj("Describe a memory you're not sure is yours."),
        dj("What's the earliest thing you can remember?"),
        dj("If you could revisit one ordinary day, which would it be?"),
        dj("What place from your childhood do you still walk in your mind?"),
        dj("What did you used to dream of becoming?"),
        dj("Describe a smell that instantly returns you somewhere."),
        dj("What's a small memory that means more than it should?"),
        dj("Who appears in your dreams that you miss when awake?"),
        dj("What does your most peaceful dream look like?"),
        dj("Describe a memory as if it happened to someone else."),
        dj("What's a moment you'd loop forever if you could?"),
        dj("What do you hope you never forget?"),
        dc("Write a story that follows dream logic and never explains itself."),
        dc("A character can enter other people's dreams. Write the first time it goes wrong."),
        dc("Write a town where everyone shares the same recurring dream."),
        dc("Describe a house you only visit while sleeping."),
        dc("Write the memory a stranger left behind in a found notebook."),
        dc("A machine records dreams. Describe the most beautiful one it captured."),
        dc("Write a scene where a forgotten memory returns at the worst possible moment."),
        dc("A character wakes with a memory of a life they never lived. Continue."),
        dc("Write about a library that lends out other people's memories."),
        dc("Describe the dream a city has when all its people are asleep."),
        dc("Write the moment a character realizes they're dreaming and chooses to stay."),
        dc("A door in a dream keeps appearing in waking life. Open it."),
        dc("Write about the last dream of someone about to wake into a changed world."),
        dc("Describe a childhood memory that turns out to be a warning."),
        dc("Write a story where memory can be traded like currency."),
        dc("A character meets, in a dream, the version of themselves they almost became."),
    ]

    static let letters: [Prompt] = [
        lj("Write a letter to yourself one year from now."),
        lj("Write the letter you wish you'd received."),
        lj("Write a thank-you note to someone who'll never read it."),
        lj("Write a letter to a younger version of you."),
        lj("Write to someone you've lost touch with."),
        lj("Write a letter to the part of you that's tired."),
        lj("Write to someone you've forgiven, or want to."),
        lj("Write a letter to a place you had to leave."),
        lj("Write to the person who believed in you first."),
        lj("Write a letter you'll never send, and mean every word."),
        lj("Write a note to your future self on a hard day."),
        lj("Write a letter to a fear, telling it what you've learned."),
        lj("Write to someone whose advice you finally understand."),
        lj("Write a letter to your body."),
        lc("Write a letter from a lighthouse keeper to the sea."),
        lc("Two characters correspond for years without ever meeting. Write one letter."),
        lc("Write a letter found in a bottle, decades after it was sent."),
        lc("Write the last letter a soldier writes home, and never sends."),
        lc("A character writes to their younger self and gets a reply. Write it."),
        lc("Write a letter of resignation from a job no one knew existed."),
        lc("Write a love letter written entirely in apologies."),
        lc("Write a letter from a ghost to the person living in their old house."),
        lc("A character writes a complaint letter to the universe. Write the universe's reply."),
        lc("Write the letter an explorer leaves at the edge of the known world."),
        lc("Write a letter that must be read in exactly the wrong order to make sense."),
        lc("Write to a stranger you'll never meet, but whose life touched yours."),
        lc("Write the recommendation letter a villain writes for a hero."),
        lc("Write a letter from the future, warning about something small."),
        lc("A character finds letters their parent never sent. Write one."),
        lc("Write a final letter that is, secretly, a beginning."),
    ]

    static let worldbuilding: [Prompt] = [
        wj("If you built a world, what's the first rule you'd insist on?"),
        wj("What does 'home' look like in your ideal world?"),
        wj("What would your world value that ours overlooks?"),
        wj("Describe the inner world you retreat to."),
        wc("Invent a city where it's illegal to be in a hurry. Describe a day there."),
        wc("Build a world where memories are visible as light around people. Show a crowd."),
        wc("Describe a society that measures wealth in stories told, not coins held."),
        wc("Invent a holiday and the strange tradition at its heart."),
        wc("Build a world with two moons and describe what that does to the nights."),
        wc("Describe the marketplace of a city that trades only in things that can't be owned."),
        wc("Invent a profession that exists only in your world. Show someone doing it."),
        wc("Build a world where the dead leave behind a single sentence. Read three."),
        wc("Describe a country divided not by borders but by which season it's always in."),
        wc("Invent a god small enough to fit in a pocket, and the person who carries it."),
        wc("Build a world where names have weight and can be lent or stolen. Continue."),
        wc("Describe the ruins of a civilization that worshipped sound."),
        wc("Invent a map's legend for a place that rearranges itself nightly."),
        wc("Build a city that floats on a lake of cloud. Describe the docks."),
        wc("Describe a culture's coming-of-age ritual involving the sea."),
        wc("Invent a magic with a precise, costly rule, and someone who pays it."),
        wc("Build a world where it rains once a year and the whole calendar bends around it."),
        wc("Describe the library at the center of your world and its strangest book."),
        wc("Invent a creature that only exists where two territories meet."),
        wc("Build a society that buries its history and a child who digs it up."),
        wc("Describe a bridge between two worlds and the toll required to cross."),
        wc("Invent a festival of forgetting. Describe who refuses to take part."),
        wc("Build a world powered by a resource that's running out. Show the last of it."),
        wc("Describe the oldest law in your world and the first person to break it."),
        wc("Invent a city whose districts are sorted by the dreams of their residents."),
        wc("Build a world where music is currency and silence is poverty. Continue."),
    ]

    static let sparks: [Prompt] = [
        sc("Begin: 'They told me the house was empty. They were wrong, but not in the way you'd think.'"),
        sc("Begin: 'The last message arrived three days after the sender died.'"),
        sc("Begin: 'Everyone in town could fly. I was the only one who chose to walk.'"),
        sc("Begin: 'She returned the library book ninety years late, and apologized.'"),
        sc("Begin: 'The map had one road, and it only went one way.'"),
        sc("Begin: 'I inherited my grandmother's recipes and one of them was a spell.'"),
        sc("Begin: 'The lighthouse had been dark for years. Tonight it lit.'"),
        sc("Begin: 'We found a door in the ocean floor, and it was knocking.'"),
        sc("Begin: 'My reflection waved first.'"),
        sc("Begin: 'The town clock struck thirteen, and only I seemed to notice.'"),
        sc("Begin: 'He sold maps to places that didn't exist yet.'"),
        sc("Begin: 'The garden grew back overnight, exactly as it had been a hundred years ago.'"),
        sc("Begin: 'The phone rang. The caller ID was my own number.'"),
        sc("Begin: 'In our family, we keep the attic locked for a reason.'"),
        sc("Begin: 'The train only stops here once. Choose carefully.'"),
        sc("Begin: 'I found a list of my own future regrets, written in my handwriting.'"),
        sc("Begin: 'The storm spelled her name across the sky.'"),
        sc("Begin: 'They built a wall to keep something in, not out.'"),
        sc("Begin: 'The museum's newest exhibit was breathing.'"),
        sc("Begin: 'Every mirror in the house showed a different year.'"),
        sc("Begin: 'The old man fed the pigeons messages, not crumbs.'"),
        sc("Begin: 'On my thirtieth birthday, the letters I never sent came back, answered.'"),
        sc("Begin: 'The river ran backward for exactly one minute.'"),
        sc("Begin: 'We weren't supposed to find the room with no door.'"),
        sc("Begin: 'The shop sold last words. Business was quiet but steady.'"),
        sc("Begin: 'My shadow stayed behind when I left.'"),
        sc("Begin: 'The snow fell upward that winter, and we learned to live with it.'"),
        sc("Begin: 'She could taste lies. Today, breakfast was bitter.'"),
        sj("What's a single sentence that could start the story of your life this year?"),
        sj("Write the opening line of the book only you could write."),
    ]

    static let seasonal: [Prompt] = [
        zj("What does this season ask you to let go of?"),
        zj("What are you harvesting in your life right now?"),
        zj("What's the first sign of the coming season where you are?"),
        zj("What do you want to plant — literally or otherwise — before this season ends?"),
        zj("How does this time of year change your daily rhythm?"),
        zj("What smell defines this season for you?"),
        zj("What did last year's version of this season teach you?"),
        zj("What are you grateful the cold (or heat) makes you slow down for?"),
        zj("What tradition do you keep when the seasons turn?"),
        zj("Where do you most feel the year passing?"),
        zj("What does the changing light do to your mood?"),
        zj("What's a small comfort that belongs only to this time of year?"),
        zc("Write about the last warm day before winter, told by someone who won't survive it."),
        zc("Describe a spring that arrives a month early and what it disturbs."),
        zc("Write the story of the first snowfall in a town that's forgotten how to be quiet."),
        zc("A character meets autumn as a person at a crossroads. Write the conversation."),
        zc("Write about a summer that refuses to end, and the town slowly going strange."),
        zc("Describe the night the seasons skip one entirely. Which, and why?"),
        zc("Write a harvest festival where the crop being gathered is something invisible."),
        zc("A character keeps one leaf from every autumn of their life. Describe the collection."),
        zc("Write the legend of why the year has four seasons and what the fifth was."),
        zc("Describe the thaw as a kind of forgiveness."),
        zc("Write about the keeper of the longest night, and the one candle they must not let go out."),
        zc("A town votes each year on when winter is allowed to begin. Write the meeting."),
        zc("Write the first day of spring from the point of view of the last patch of snow."),
        zc("Describe a midsummer night when the sun forgets to set."),
        zc("Write the story told around the first fire of the cold season."),
        zc("A character is born on the exact turn of the year and grows up between two seasons. Continue."),
        zc("Write about the day the leaves all fall at once, on schedule, by appointment."),
        zc("Describe the smell of the world the morning the first frost arrives."),
    ]
}
