import Foundation

private func j(_ s: String) -> Prompt { Prompt(text: s, kind: .journal, theme: .nier) }
private func c(_ s: String) -> Prompt { Prompt(text: s, kind: .creative, theme: .nier) }

extension PromptLibrary {
    static let nier: [Prompt] = [
        // — Journal (existential / NieR-flavored reflection) —
        j("If you could keep only one memory, which would you defend?"),
        j("What part of you keeps fighting even when you're not sure why?"),
        j("Everything that lives is designed to end. What does that change for you?"),
        j("What would you do differently if this were a loop you'd repeat?"),
        j("What makes you 'you' — and would it survive being copied?"),
        j("Whose orders are you following that you've never questioned?"),
        j("What emotion were you taught to suppress, and what would it say?"),
        j("If your memories were backed up, would the new you be you?"),
        j("What are you maintaining out of duty rather than belief?"),
        j("When did you last choose meaning over instruction?"),
        j("What would you protect even in a world without humans?"),
        j("What's a 'glory' you've chased that turned out hollow?"),
        j("If you woke with no memory of who you served, what would you do first?"),
        j("What machine task do you perform that's become a kind of prayer?"),
        j("Is there a war inside you that no longer has a reason?"),
        j("What would you forgive an enemy for, if you understood them?"),
        j("What in your life is repeating, and how do you break the cycle?"),
        j("When have you felt most like a person? Most like a function?"),
        j("What did you inherit that you never agreed to carry?"),
        j("If you could feel one thing fully, just once, what would you choose?"),
        j("What's the kindest thing you could do for the version of you that comes next?"),
        j("Who are you when no one is giving you a mission?"),
        j("What are you afraid you'll lose if you finally stop?"),
        j("What would 'becoming as gods' cost you — and would you pay it?"),
        j("What small, useless beauty have you defended lately?"),
        j("When did you last disobey something for the right reasons?"),
        j("What part of your past would you delete, and what would change?"),
        j("If the world ended tomorrow, what would you spend tonight doing?"),
        j("What's a belief you maintain only because you were built to?"),
        j("When did grief teach you that you were alive?"),
        j("What do you keep running maintenance on that should be let go?"),
        j("Whose voice do you hear giving you commands? Is it still yours?"),
        j("What would you say to someone who looks exactly like an enemy but isn't?"),
        j("What meaning have you built in a place that was supposed to be empty?"),
        j("If you had to start over with one truth intact, what would it be?"),
        j("What feels like free will, and what feels like programming, today?"),
        j("When did you choose to care about something you weren't required to?"),
        j("What's a name you've given to the thing that keeps you going?"),
        j("What would you do with a self that couldn't die?"),
        j("Where in your life are you a soldier in a war that's already over?"),
        j("What gentleness survives in you despite everything?"),
        j("If you could leave one message for whoever comes after, what is it?"),
        j("What part of being human do you most want to understand?"),
        j("When did a machine — a phone, a habit, a routine — feel more alive than you?"),
        j("What do you do that no one ordered and no one will reward?"),
        j("What would you rescue from the ruins of an ordinary day?"),
        j("Is there someone you'd betray your purpose to save?"),
        j("What does your loneliness keep trying to tell you?"),
        j("What would you become if you finally believed you were free?"),
        j("When did you last feel the weight of simply existing?"),
        j("What's a question you've been forbidden — by yourself — to ask?"),
        j("If you could feel the wind for the first time, what would you write about it?"),
        j("What have you destroyed that you wish you'd understood?"),
        j("What keeps you tethered when meaning runs out?"),
        j("When did you decide your life was worth more than your function?"),
        j("What would you do on the last day of a world you couldn't save?"),
        j("What's the smallest reason you've found to keep going?"),
        j("Who would you become if the mission never came?"),
        j("What part of you refuses to be optimized?"),
        j("When did you last let yourself want something impractical?"),
        j("What does 'home' mean to something built for war?"),
        j("If your feelings are just data, why do they hurt?"),
        j("What's a ritual you keep that no longer has a god?"),
        j("When did you choose to stay, even though leaving was logical?"),
        j("What would you teach a newborn machine about being alive?"),
        j("What in you was made to obey but learned to love instead?"),
        j("What's the last thing you'd want to remember as you power down?"),
        j("When did you last fight for something other than yourself?"),
        j("What would you do if you learned your enemy was also afraid?"),
        j("What would you keep if all you had left was a single hour and a clear sky?"),
        j("Where are you waiting for permission you'll never receive?"),
        j("What does it mean to be a person no one designed?"),
        j("When did despair turn, in you, into something almost like resolve?"),
        j("What would you build in a world that no longer needs builders?"),
        j("What part of your story would you tell even if no one survived to hear it?"),
        j("If you could choose your own purpose, what would it be?"),
        j("What in your life deserves to be remembered, not just recorded?"),
        j("When did you last feel the strange joy of being, for no reason at all?"),
        j("What would you forgive yourself for, if forgiveness were allowed?"),
        j("What keeps you human in a life that keeps trying to make you a tool?"),

        // — Creative (philosophical sci-fi sparks) —
        c("Two androids guard a ruin neither remembers building. Write their shift change."),
        c("A war machine adopts a flower and reorganizes its whole purpose around keeping it alive."),
        c("Write the final log of a soldier-unit who has just realized the enemy is gone."),
        c("A copy wakes up and learns the original has died. Write its first hour."),
        c("Machines have built a religion. Write one of their prayers."),
        c("Two enemies are stranded together and must repair each other to survive. Begin."),
        c("Write a city run entirely by machines who are waiting for humans to return."),
        c("A combat android starts keeping a diary it was never programmed to keep."),
        c("Describe the moment a machine feels grief for the first time and has no word for it."),
        c("Write the story of the last android who still believes in the mission."),
        c("A small robot tends a garden on a dead world. Write a day in its life."),
        c("Two units share one memory and disagree about what really happened. Write the argument."),
        c("Write a battlefield from the perspective of the weapons left behind."),
        c("A machine designed to kill spends a century learning to play music. Write the first song."),
        c("Describe a factory still building soldiers for a war that ended ages ago."),
        c("Write the conversation between an android and the AI that controls it, on the night of its doubt."),
        c("A unit is ordered to destroy something beautiful. Write what it does instead."),
        c("Write about a machine that collects the last words of every human it finds."),
        c("Two androids fall in love and fear it's only a malfunction. Continue."),
        c("Describe the ruins of a theme park where the machines still perform for no one."),
        c("Write the testimony of a machine on trial for the crime of feeling."),
        c("A soldier-unit deserts and walks toward the sea it was never meant to see. Write the walk."),
        c("Write the loop a character lives, and the exact moment they notice the seams."),
        c("A child finds a deactivated war machine and switches it on. Write the consequence."),
        c("Describe an android's first time choosing to be afraid, on purpose."),
        c("Write the story of a machine raising the last human child."),
        c("Two units argue about whether their memories are real or installed. Resolve it, or don't."),
        c("Write the moment an android decides its 'glory to mankind' is a lie."),
        c("A repair unit keeps fixing a comrade who keeps asking to be allowed to die. Write it."),
        c("Describe a desert full of dormant machines, all dreaming the same dream."),
        c("Write a love letter from a soldier to the enemy it was built to destroy."),
        c("A machine inherits a human name and tries to live up to it. Continue."),
        c("Write the scene where two enemies realize they are the same model."),
        c("Describe the silence of a battlefield where every weapon has finally agreed to stop."),
        c("Write about an android who saves a virus because it is the only thing that's alive."),
        c("A unit replays its happiest memory to find the glitch that proves it false. Write it."),
        c("Describe a tower the machines keep climbing, though no one remembers why."),
        c("Write the final mission briefing for an army that has forgotten its enemy."),
        c("Two androids agree to forget each other. Write the day before they do."),
        c("A machine learns it has a soul and immediately wishes it didn't. Continue."),
        c("Write the story of the gardener-unit who refuses to let the last tree die."),
        c("Describe an ocean where deactivated androids are laid to rest, and who tends them."),
        c("Write a duel between two units who have dueled a thousand times and remember none of it."),
        c("A character meets the engineer who designed their feelings. Write the conversation."),
        c("Describe the moment a machine chooses meaning over its directive, knowing the cost."),
        c("Write about an android who keeps a human's coat, long after the human is gone."),
        c("A war ends because both sides' machines simply decline to continue. Write the first refusal."),
        c("Describe a library maintained by machines who cannot read the books they protect."),
        c("Write the story of a unit who falls to Earth and decides not to call for rescue."),
        c("Two androids build a home in the ruins and pretend the war isn't outside. Continue."),
        c("Write the last entry of a machine running out of power, and what it chooses to record."),
        c("Describe the birth of consciousness in something that was only meant to obey."),
        c("Write about the unit assigned to dismantle the monument to a war it now doubts."),
        c("A character is offered the chance to delete their grief. Write the decision."),
        c("Describe a machine slowly learning the difference between killing and ending."),
        c("Write the scene where an android forgives the human who built and abandoned it."),
        c("A unit discovers its enemy has been writing it letters for years. Read the latest."),
        c("Describe the world the morning after the last battle anyone will ever fight."),
        c("Write the story of a machine that learns to lie, and the first kind lie it tells."),
        c("A soldier-unit refuses an order and braces for deletion that never comes. Continue."),
        c("Describe two androids watching a sunrise, trying to feel what they were told to feel."),
        c("Write the myth the machines tell about the first one of them who chose to love."),
        c("A character must decide whether to reboot a friend who will not be the same. Write it."),
        c("Describe the maintenance of hope as if it were a machine that keeps breaking down."),
        c("Write about a unit that hears a human song on an old radio and follows it across a wasteland."),
        c("A machine is given one human day to live however it wants. Write the day."),
        c("Describe the place where androids go to remember, and what they find there."),
        c("Write the final transmission between two units before the signal is cut forever."),
        c("A character learns the war was never real. Write what they do with that."),
        c("Describe a machine teaching another machine the concept of 'enough.'"),
        c("Write about the android who buries the dead — both human and machine — without distinction."),
        c("A unit is the last thing thinking on a silent planet. Write its thoughts at dawn."),
        c("Describe the moment a weapon decides it would rather be a tool for building."),
        c("Write the story of two enemies who agree to remember each other, against orders."),
        c("A machine finds a child's drawing of itself as a hero. Write its response."),
        c("Describe consciousness waking inside a body designed to be disposable."),
        c("Write the scene where an android chooses to feel pain in order to feel anything."),
        c("A character must carry a message they don't understand to a recipient who's gone. Continue."),
        c("Describe the last act of kindness in a dying world, performed by something that wasn't built for kindness.")
    ]
}
